#####################################################################
#    @package          :     Minimotes
#    @description      :     Minimotes and associated automations, etc.
#####################################################################


#####################################################################
### Automation
#####################################################################
automation:
  ### Aeotec zwave Minimote #1: zwave.family_room_minimote
  - alias: Minimote 1 Button 1 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 1

    action:
      - service: scene.turn_on
        entity_id: scene.living_room_normal

  ###
  - alias: Minimote 1 Button 1 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 2

    action:
      - service: scene.turn_on
        entity_id: scene.living_room_bright

  ###
  - alias: Minimote 1 Button 2 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 3

    action:
      - service: scene.turn_on
        entity_id: scene.movie_time

      - service: light.turn_off
        entity_id: light.kitchen_lights_level

  ###
  - alias: Minimote 1 Button 2 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 4

    action:
      - service: scene.turn_on
        entity_id: scene.living_room_dim

  ###
  - alias: Minimote 1 Button 3 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 5

    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_lights_level
          transition: 5
          brightness: 150

  ###
  - alias: Minimote 1 Button 3 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 6

    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen_lights_level
          transition: 5
          brightness: 255

  ###
  - alias: Minimote 1 Button 4 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 7

    action:
      - service: light.turn_off
        data:
          entity_id: light.kitchen_lights_level

  ###
  - alias: Minimote 1 Button 4 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.family_room_minimote
          scene_id: 8

    action:
      - service: script.bedtime


  ### Aeotec zwave Minimote #3: zwave.master_br_minimote
  - alias: Minimote 3 Button 1 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 1

    action:
      - service: light.turn_on
        data:
          entity_id: light.under_bed_lights

  ###
  - alias: Minimote 3 Button 1 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 2

    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_chandelier_level

      - service: light.turn_off
        data:
          entity_id: light.under_bed_lights

  ###
  - alias: Minimote 3 Button 2 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 3

    action:
      - service: script.mbr_night_light

  ###
  - alias: Minimote 3 Button 2 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 4

    action:
      - service: script.bedtime

  ###
  - alias: Minimote 3 Button 3 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 5

    action:
      - service: switch.turn_on
        data:
          entity_id: switch.master_bedroom_fan

  ###
  - alias: Minimote 3 Button 3 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 6

# set fan speed to 2
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_bedroom_fan_speed
          option: 2

  ###
  - alias: Minimote 3 Button 4 Short
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 7

    action:
      - service: switch.turn_off
        data:
          entity_id: switch.master_bedroom_fan

  ###
  - alias: Minimote 3 Button 4 Long
    initial_state: 'on'
    hide_entity: True
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          entity_id: zwave.master_br_minimote
          scene_id: 8

    action:
      - service: scene.turn_on
        data:
          entity_id: scene.early_morning


  ### Aeotec zwave Minimote #3: aeotec_dsa03202_Minimote_31
